function vecq = rayleigh(~,q,baseT,~,baseU,baseUdash,baseUdashdash,alpha,...
    ktilde,M,c,gamma,Tb)
    vecq(1) = q(2);
    %vecq(2) = 2*baseUdash*q(2)/(baseU-c) ...
    %    + ktilde^2*baseT*(baseT-alpha^2*M^2*(baseU-c)^2/ktilde^2)*q(1);
    vecq(2) = 2*(0.5*(gamma-1)*(Tb+1)*baseUdashdash*q(2))/...
        (0.5*(gamma-1)*(Tb+1)*baseUdash-c) ...
        + ktilde^2*(1-(0.5*(gamma-1)*(Tb+1)*baseUdash)^2)*q(1);
    
    