function [eta, p] = RK(a,b,deltaeta,bcs,rayleigh,baseT,baseTdash,baseU,...
        baseUdash,baseUdashdash,c,gamma,Tb,khat)
    
    eta = a:deltaeta:b; 
    n = length(eta);
    p = zeros(length(bcs),n);
    p(:,n) = bcs;
    
    for k = n-1:-1:1 
        k1 = rayleigh(eta(k+1),p(:,k+1),baseT(k+1),baseTdash(k+1),baseU(k+1),...
        baseUdash(k+1),baseUdashdash(k+1),c,gamma,Tb,khat);
        k2 = rayleigh(eta(k+1)-0.5*deltaeta,p(:,k+1)-0.5*deltaeta*k1',baseT(k+1),...
            baseTdash(k+1),baseU(k+1),baseUdash(k+1),baseUdashdash(k+1),...
            c,gamma,Tb,khat);
        k3 = rayleigh(eta(k+1)-0.5*deltaeta,p(:,k+1)-0.5*deltaeta*k2',baseT(k+1),...
            baseTdash(k+1),baseU(k+1),baseUdash(k+1),baseUdashdash(k+1),...
            c,gamma,Tb,khat);
        k4 = rayleigh(eta(k+1)-deltaeta,p(:,k+1)-deltaeta*k3',baseT(k+1),baseTdash(k+1),...
            baseU(k+1),baseUdash(k+1),baseUdashdash(k+1),c,...
            gamma,Tb,khat);
        p(:,k)=p(:,k+1)-deltaeta*(k1'+2*k2'+2*k3'+k4')/6;
    end