function [eta, p] = RK(a,b,deltaeta,bcs,rayleigh,baseT,baseTdash,baseU,...
        baseUdash,baseUdashdash,c,gamma,Tb,khat)
    
    eta = a:deltaeta:b; 
    n = length(eta);
    p = zeros(length(bcs),n);
    p(:,1) = bcs;
    
    for k = 1:(n-1) 
        k1 = rayleigh(eta(k),p(:,k),baseT(k),baseTdash(k),baseU(k),...
        baseUdash(k),baseUdashdash(k),c,gamma,Tb,khat);
        k2 = rayleigh(eta(k)+0.5*deltaeta,p(:,k)+0.5*deltaeta*k1',baseT(k),...
            baseTdash(k),baseU(k),baseUdash(k),baseUdashdash(k),...
            c,gamma,Tb,khat);
        k3 = rayleigh(eta(k)+0.5*deltaeta,p(:,k)+0.5*deltaeta*k2',baseT(k),...
            baseTdash(k),baseU(k),baseUdash(k),baseUdashdash(k),...
            c,gamma,Tb,khat);
        k4 = rayleigh(eta(k)+deltaeta,p(:,k)+deltaeta*k3',baseT(k),baseTdash(k),...
            baseU(k),baseUdash(k),baseUdashdash(k),c,...
            gamma,Tb,khat);
        p(:,k+1)=p(:,k)+deltaeta*(k1'+2*k2'+2*k3'+k4')/6;
    end